### ISSUE TITLE
Netlify rejecting cookie from the server

### ISSUE THREAD

**Issue by AntonEmery** [AntonEmery/chord-app#61]
The server is returning a successful 200 from the backend when logging in, but Netlify is rejecting the `connect.sid` cookie that Node sends.  This cookie is used to check for login state

**Error**
```
Cookie “connect.sid” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite
```
Will need to research and probably set the `SameSite` attribute to the correct value

**Comment by AntonEmery** [comment]
I merged in that PR but no luck.  I think I saw the error in the console, though I'm not seeing it now.

**Comment by XiXiaPdx** [comment]
Ok, acceptance criteria for this issue is to verify the cookie returned by the server is in the browser. 

If so, how is verification done?

**Comment by AntonEmery** [comment]
When I am running the app locally I can see the cookie in Chrome Dev Tools under Application. then select Cookies from the left hand column.  But I don't see it when testing the production app

**Comment by XiXiaPdx** [comment]
Ok, that apt-get command. doesn't work because I think we are using nginx , not nginx PLUS. 

I've seen two options here and they both involve modifying the nginx server. 

This one involves a config file or two. 
https://stackoverflow.com/questions/48880738/how-to-set-secure-attribute-to-set-cookie-in-nginx-through-nginx-conf-file


 **Alternative solution:** 

The overflow above mentions the alternative, which is to go the nginx source files and rebuild them while adding the correct third-party module to it. 

The really simple and lacking all the important details of this process is here
https://geekflare.com/httponly-secure-cookie-nginx/

docs on how to build nginx from source
https://docs.nginx.com/nginx/admin-guide/installing-nginx/installing-nginx-open-source/#sources

the module to build the nginx server with
https://github.com/AirisX/nginx_cookie_flag_module/blob/c4ff449318474fbbb4ba5f40cb67ccd54dc595d4/README.md

**Comment by AntonEmery** [comment]
I just tried that first link, but was unable to restart the Nginx server after I made those changes

**Comment by AntonEmery** [comment]
So I've set the front end to `chord-app.com` and the back end to `api.chord-app.com`
This commit https://github.com/AntonEmery/chord-app/commit/c65868b4ab04ccac0594d8d6806b443254eb9138 updates the cookie to `sameSite: strict`, since the two parts of the app are on the same domain

Still no luck, on initial login attempt I can see the cookie in the response.  But I still don't see it under the Application tab in Chrome.  I'll have to ask around, not sure what else to try.
